const keys=['title','policy','startup','manual','periodic','interval','hours','channel','stable','preview','auto_download','check','download','cancel','later','install','official','current','candidate','blocked','deferred','idle','checking','available','downloading','ready','failed','cancelled','loading','next','healthy','no_candidate','available_v','downloading_p','ready_v','failed_e','last_checked','never','whats_new','notes_title','notes_empty','notes_more','pill','pill_later','restarting','confirm_title','confirm_busy','confirm_update','confirm_cancel','updated_to','not_installed','no_trust','install_on_quit','close'];
const copy={
en:['Updates','When to check','When Versora starts','Only when I check','At launch and every few hours','Interval','hours','Release channel','Stable','Preview','Download and install updates automatically','Check for updates','Download','Cancel','Later','Restart and update','Open the official release page','Current version','Available version','Authenticated self-update is unavailable.','Deferred until you choose to continue.',"You're up to date",'Checking…','Update available','Downloading','Ready to install','Error','Cancelled','Loading update settings…','Next check','Highest healthy version','No newer release in this channel.','Version {v} is available','Downloading {p}%','{v} is ready','Error: {e}','Last checked','Not yet',"What's new","What's new in {v}",'This release has no notes.','Read the full notes','Version {v} · Restart','Later','Restarting…','Update Versora','Work is in progress, and restarting will interrupt it. Update anyway?','Update','Cancel','Updated to {v}','Updates only work in the installed Versora app.',"This copy can't install updates by itself. Get new versions from the official release page.",'It installs when you quit Versora, or restart now.','Close'],
'zh-Hant':['更新','幾時檢查','Versora 啟動時','只喺我手動檢查時','啟動時同每隔幾個鐘','相隔','小時','版本通道','穩定版','預覽版','自動下載同安裝更新','檢查更新','下載','取消','稍後','重新啟動並更新','開官方下載頁','目前版本','可用版本','已驗證的自動更新尚未開放。','已延後，待你選擇繼續。','已經係最新','檢查緊…','有新版本','下載緊','已準備好','出錯','已取消','正在載入更新設定…','下次檢查','最高健康啟動版本','此通道沒有較新版本。','有新版本 {v}','下載緊 {p}%','{v} 已準備好','出錯：{e}','上次檢查','未檢查過','有咩新','{v} 有咩新','呢個版本冇附更新說明。','睇晒全部說明','新版本 {v} · 重新啟動','稍後','重新啟動緊…','更新 Versora','而家有工作做緊，重新啟動會中斷。照樣更新？','更新','取消','已更新到 {v}','更新只可以喺已安裝嘅 Versora 用。','呢個版本唔可以自己安裝更新，請到官方下載頁攞新版本。','閂 Versora 嘅時候會自動安裝，或者而家重新啟動。','關閉'],
'zh-Hans':['更新','何时检查','Versora 启动时','仅手动检查','启动时及每隔几小时','间隔','小时','版本通道','稳定版','预览版','自动下载并安装更新','检查更新','下载','取消','稍后','重新启动并更新','打开官方下载页','当前版本','可用版本','已验证的自动更新尚未开放。','已推迟，等待你选择继续。','已是最新版本','正在检查…','有更新可用','正在下载','准备安装','失败','已取消','正在加载更新设置…','下次检查','最高健康启动版本','此通道没有更新版本。','有新版本 {v}','正在下载 {p}%','{v} 已准备好','出错：{e}','上次检查','尚未检查','更新内容','{v} 更新内容','此版本没有更新说明。','查看完整说明','新版本 {v} · 重新启动','稍后','正在重新启动…','更新 Versora','目前有工作正在进行，重新启动会中断。仍要更新？','更新','取消','已更新到 {v}','更新仅适用于已安装的 Versora。','此版本无法自行安装更新，请到官方下载页获取新版本。','退出 Versora 时会自动安装，或立即重新启动。','关闭'],
ja:['更新','更新の確認','Versora の起動時','手動で確認する時のみ','定期的に','間隔','時間','リリースチャンネル','安定版','プレビュー','自動でダウンロード','今すぐ確認','ダウンロード','キャンセル','後で','今すぐ更新','公式リリースを開く','現在のバージョン','利用可能なバージョン','認証済みの自動更新はまだ利用できません。','続行を選ぶまで延期します。','最新の状態です','確認中','更新があります','ダウンロード中','インストールの準備完了','失敗','キャンセル済み','更新設定を読み込み中…','次の確認','正常起動した最高バージョン','このチャンネルに新しいリリースはありません。'],
ko:['업데이트','업데이트 확인','Versora 시작 시','직접 확인할 때만','주기적으로','간격','시간','출시 채널','안정 버전','미리보기','자동 다운로드','지금 확인','다운로드','취소','나중에','지금 업데이트','공식 출시 페이지 열기','현재 버전','사용 가능한 버전','인증된 자동 업데이트는 아직 사용할 수 없습니다.','계속하기를 선택할 때까지 연기됩니다.','최신 버전','확인 중','업데이트 가능','다운로드 중','설치 준비됨','실패','취소됨','업데이트 설정을 불러오는 중…','다음 확인','정상 시작한 가장 높은 버전','이 채널에 더 최신 버전이 없습니다.'],
es:['Actualizaciones','Buscar actualizaciones','Al iniciar Versora','Solo manualmente','Periódicamente','Intervalo','horas','Canal de versiones','Estable','Vista previa','Descargar automáticamente','Buscar ahora','Descargar','Cancelar','Más tarde','Actualizar ahora','Abrir versiones oficiales','Versión actual','Versión disponible','La actualización autenticada aún no está disponible.','Pospuesto hasta que decidas continuar.','Actualizado','Buscando','Actualización disponible','Descargando','Listo para instalar','Error','Cancelado','Cargando ajustes…','Próxima búsqueda','Mayor versión iniciada correctamente','No hay una versión más reciente en este canal.'],
fr:['Mises à jour','Vérifier les mises à jour','Au démarrage de Versora','Manuellement uniquement','Périodiquement','Intervalle','heures','Canal de publication','Stable','Aperçu','Télécharger automatiquement','Vérifier maintenant','Télécharger','Annuler','Plus tard','Mettre à jour','Ouvrir les versions officielles','Version actuelle','Version disponible','La mise à jour authentifiée n’est pas encore disponible.','Reportée jusqu’à votre décision de continuer.','À jour','Vérification','Mise à jour disponible','Téléchargement','Prête à installer','Échec','Annulée','Chargement des réglages…','Prochaine vérification','Plus haute version démarrée correctement','Aucune version plus récente sur ce canal.'],
de:['Updates','Nach Updates suchen','Beim Start von Versora','Nur manuell','Regelmäßig','Intervall','Stunden','Versionskanal','Stabil','Vorschau','Automatisch herunterladen','Jetzt prüfen','Herunterladen','Abbrechen','Später','Jetzt aktualisieren','Offizielle Veröffentlichungen öffnen','Aktuelle Version','Verfügbare Version','Authentifizierte Selbstupdates sind noch nicht verfügbar.','Verschoben, bis Sie fortfahren.','Aktuell','Prüfung läuft','Update verfügbar','Download läuft','Installationsbereit','Fehlgeschlagen','Abgebrochen','Updateeinstellungen werden geladen…','Nächste Prüfung','Höchste erfolgreich gestartete Version','Keine neuere Version in diesem Kanal.'],
pt:['Atualizações','Procurar atualizações','Ao iniciar o Versora','Apenas manualmente','Periodicamente','Intervalo','horas','Canal de versões','Estável','Pré-visualização','Descarregar automaticamente','Verificar agora','Descarregar','Cancelar','Mais tarde','Atualizar agora','Abrir versões oficiais','Versão atual','Versão disponível','A atualização autenticada ainda não está disponível.','Adiada até decidir continuar.','Atualizado','A verificar','Atualização disponível','A descarregar','Pronto para instalar','Falhou','Cancelado','A carregar definições…','Próxima verificação','Maior versão iniciada com sucesso','Não há versão mais recente neste canal.'],
vi:['Cập nhật','Kiểm tra cập nhật','Khi Versora khởi động','Chỉ khi kiểm tra thủ công','Định kỳ','Khoảng thời gian','giờ','Kênh phát hành','Ổn định','Xem trước','Tự động tải xuống','Kiểm tra ngay','Tải xuống','Hủy','Để sau','Cập nhật ngay','Mở bản phát hành chính thức','Phiên bản hiện tại','Phiên bản có sẵn','Chưa có cập nhật tự động được xác thực.','Hoãn cho đến khi bạn chọn tiếp tục.','Đã cập nhật','Đang kiểm tra','Có bản cập nhật','Đang tải xuống','Sẵn sàng cài đặt','Thất bại','Đã hủy','Đang tải cài đặt…','Lần kiểm tra tiếp theo','Phiên bản cao nhất đã khởi động tốt','Không có phiên bản mới hơn trong kênh này.'],
th:['อัปเดต','ตรวจสอบอัปเดต','เมื่อ Versora เริ่มทำงาน','เมื่อฉันตรวจสอบเองเท่านั้น','เป็นระยะ','ช่วงเวลา','ชั่วโมง','ช่องทางรุ่น','เสถียร','ทดลอง','ดาวน์โหลดอัตโนมัติ','ตรวจสอบตอนนี้','ดาวน์โหลด','ยกเลิก','ภายหลัง','อัปเดตตอนนี้','เปิดรุ่นอย่างเป็นทางการ','รุ่นปัจจุบัน','รุ่นที่พร้อมใช้','การอัปเดตอัตโนมัติที่ยืนยันแล้วยังไม่พร้อมใช้','เลื่อนไว้จนกว่าคุณจะเลือกดำเนินการต่อ','เป็นรุ่นล่าสุด','กำลังตรวจสอบ','มีอัปเดต','กำลังดาวน์โหลด','พร้อมติดตั้ง','ล้มเหลว','ยกเลิกแล้ว','กำลังโหลดการตั้งค่า…','ตรวจสอบครั้งถัดไป','รุ่นสูงสุดที่เริ่มทำงานได้ปกติ','ไม่มีรุ่นใหม่กว่าในช่องทางนี้'],
id:['Pembaruan','Periksa pembaruan','Saat Versora dimulai','Hanya secara manual','Secara berkala','Interval','jam','Saluran rilis','Stabil','Pratinjau','Unduh otomatis','Periksa sekarang','Unduh','Batal','Nanti','Perbarui sekarang','Buka rilis resmi','Versi saat ini','Versi tersedia','Pembaruan mandiri terautentikasi belum tersedia.','Ditunda hingga Anda memilih untuk melanjutkan.','Sudah terbaru','Memeriksa','Pembaruan tersedia','Mengunduh','Siap dipasang','Gagal','Dibatalkan','Memuat pengaturan…','Pemeriksaan berikutnya','Versi tertinggi yang berhasil dimulai','Tidak ada rilis yang lebih baru di saluran ini.'],
};
// Locales without a newer string fall back to English.
export function updateTranslation(key,language){const index=keys.indexOf(key.replace(/^updates\./,''));return index<0?null:(copy[language]||copy.en)[index]??copy.en[index];}
